# Generated by Django 2.1.5 on 2019-02-21 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCV',
            fields=[
                ('bio', models.CharField(blank=True, max_length=500, null=True, verbose_name="What's your goal?")),
                ('created_at', models.DateField(editable=False)),
                ('edited_at', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Base_CV',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu', models.CharField(max_length=25, null=True)),
            ],
            options={
                'db_table': 'eduhist',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=15, null=True)),
                ('iso_code', models.CharField(max_length=2, null=True)),
            ],
            options={
                'db_table': 'languages',
                'ordering': ('language',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ('skill',),
            },
        ),
        migrations.CreateModel(
            name='WorkHist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'workhist',
                'ordering': ('business',),
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('basecv_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BetterResume.BaseCV')),
                ('proficiency', models.IntegerField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('validated', models.BooleanField()),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField()),
                ('term_start', models.DateField(null=True)),
                ('term_end', models.DateField(null=True)),
            ],
            options={
                'db_table': 'profiles',
            },
            bases=('BetterResume.basecv',),
        ),
        migrations.AddField(
            model_name='workhist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WorkHistory', to='BetterResume.CV'),
        ),
        migrations.AddField(
            model_name='skills',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='BetterResume.CV'),
        ),
        migrations.AddField(
            model_name='languages',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Languages', to='BetterResume.CV'),
        ),
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EducationHistory', to='BetterResume.CV'),
        ),
    ]
