# Generated by Django 2.1.5 on 2019-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecv',
            name='edited_at',
            field=models.DateField(null=True),
        ),
    ]
