# Generated by Django 2.1.5 on 2019-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0002_auto_20190221_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecv',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
