# Generated by Django 2.1.5 on 2019-02-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0003_auto_20190221_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='proficiency',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='review',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='term_end',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='term_start',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='validated',
        ),
        migrations.RemoveField(
            model_name='education',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='workhist',
            name='profile',
        ),
        migrations.AddField(
            model_name='cv',
            name='eduhist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.Education'),
        ),
        migrations.AddField(
            model_name='cv',
            name='langs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.Languages'),
        ),
        migrations.AddField(
            model_name='cv',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.Skills'),
        ),
        migrations.AddField(
            model_name='cv',
            name='wrkhist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.WorkHist'),
        ),
        migrations.AddField(
            model_name='education',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(default='Beginner', max_length=25),
        ),
        migrations.AddField(
            model_name='skills',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workhist',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workhist',
            name='review',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workhist',
            name='term_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workhist',
            name='term_start',
            field=models.DateField(null=True),
        ),
    ]
