# Generated by Django 2.1.5 on 2019-02-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0004_auto_20190221_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='eduhist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.Education', verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='langs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.Languages', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.Skills', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='wrkhist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='BetterResume.WorkHist', verbose_name='Work Experience'),
        ),
    ]
