# Generated by Django 2.1.5 on 2019-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0005_auto_20190221_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
