# Generated by Django 2.1.5 on 2019-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0006_auto_20190221_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12),
        ),
    ]
