# Generated by Django 2.1.5 on 2019-02-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BetterResume', '0007_auto_20190221_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education'},
        ),
    ]
